apiVersion: apps/v1
kind: Deployment
metadata:
    name: news-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: news
    template:
        metadata:
            labels:
                app: news
        spec:
            containers:
                - name: news
                  image: us.gcr.io/horizontal-ally-289721/news
                  env: 
                    - name: MONGO_URI
                      value: 'mongodb://news-mongo-srv:27017/news'
                    - name: JWT_KEY
                      valueFrom:
                        secretKeyRef:
                            name: jwt-secret
                            key: JWT_KEY
                    - name: ADMIN_KEY
                      valueFrom:
                        secretKeyRef:
                            name: admin-secret
                            key: password
                    - name: NATS_CLIENT_ID
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: NATS_URL
                      value: 'http://nats-srv:4222'
                    - name: NATS_CLUSTER_ID
                      value: msdpalbackendapi
---
apiVersion: v1
kind: Service
metadata:
    name: news-srv
spec:
    selector:
        app: news
    ports:
        - name: news
          protocol: TCP
          port: 3000
          targetPort: 3000