apiVersion: apps/v1
kind: Deployment
metadata:
    name: posts-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: posts
    template:
        metadata:
            labels:
                app: posts
        spec:
            containers:
                - name: posts
                  image: us.gcr.io/horizontal-ally-289721/posts
                  env: 
                    - name: MONGO_URI
                      value: 'mongodb://posts-mongo-srv:27017/posts'
                    - name: JWT_KEY
                      valueFrom:
                        secretKeyRef:
                            name: jwt-secret
                            key: JWT_KEY
                    - name: ADMIN_KEY
                      valueFrom:
                        secretKeyRef:
                            name: admin-secret
                            key: password
                    - name: NATS_CLIENT_ID
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: NATS_URL
                      value: 'http://nats-srv:4222'
                    - name: NATS_CLUSTER_ID
                      value: msdpalbackendapi
---
apiVersion: v1
kind: Service
metadata:
    name: posts-srv
spec:
    selector:
        app: posts
    ports:
        - name: posts
          protocol: TCP
          port: 3000
          targetPort: 3000