apiVersion: apps/v1
kind: Deployment
metadata:
    name: query-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: query
    template:
        metadata:
            labels:
                app: query
        spec:
            containers:
                - name: query
                  image: us.gcr.io/horizontal-ally-289721/query
                  env: 
                    - name: MONGO_URI
                      value: 'mongodb://query-mongo-srv:27017/query'
                    - name: JWT_KEY
                      valueFrom:
                        secretKeyRef:
                            name: jwt-secret
                            key: JWT_KEY
                    - name: ADMIN_KEY
                      valueFrom:
                        secretKeyRef:
                            name: admin-secret
                            key: password
---
apiVersion: v1
kind: Service
metadata:
    name: query-srv
spec:
    selector:
        app: query
    ports:
        - name: query
          protocol: TCP
          port: 3000
          targetPort: 3000